# Generated by Django 2.1 on 2020-02-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Individual occupying room', max_length=50)),
                ('role', models.CharField(choices=[('ADM', 'Administrator'), ('LEC', 'Lecturer'), ('STD', 'Student'), ('STF', 'Staff')], help_text='Position of occupant', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Room (eg. Conference Hall)', max_length=50)),
                ('floor', models.CharField(choices=[('G', 'Ground'), ('1st', 'One'), ('2nd', 'Two'), ('3rd', 'Three')], default='G', help_text='Floor of the Room', max_length=1)),
                ('capacity', models.IntegerField(help_text='Enter the number of maximum number of people that can be accommodated at a time')),
                ('utilities', models.CharField(help_text='Additional Utilities', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('B', 'Booked'), ('A', 'Available'), ('M', 'Maintainance')], help_text='Status of the Room', max_length=50)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('occupant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Occupant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of Room', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Type'),
        ),
        migrations.AddField(
            model_name='occupant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Room'),
        ),
    ]
